In [88]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [89]:
df=pd.read_csv(r'C:\Users\DELL\Downloads\Netflix_Data.csv',header=0)

In [90]:
df

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,15-12-2021,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,01-03-2022,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,25-02-2022,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,24-11-2021,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,22-12-2021,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...
...,...,...,...,...,...,...,...,...,...
9832,15-10-1973,Badlands,A dramatization of the Starkweather-Fugate kil...,13.357,896,7.6,en,"Drama, Crime",https://image.tmdb.org/t/p/original/z81rBzHNgi...
9833,01-10-2020,Violent Delights,A female vampire falls in love with a man she ...,13.356,8,3.5,es,Horror,https://image.tmdb.org/t/p/original/4b6HY7rud6...
9834,06-05-2016,The Offering,When young and successful reporter Jamie finds...,13.355,94,5.0,en,"Mystery, Thriller, Horror",https://image.tmdb.org/t/p/original/h4uMM1wOhz...
9835,31-03-2021,The United States vs. Billie Holiday,Billie Holiday spent much of her career being ...,13.354,152,6.7,en,"Music, Drama, History",https://image.tmdb.org/t/p/original/vEzkxuE2sJ...
9836,23-09-1984,Threads,Documentary style account of a nuclear holocau...,13.354,186,7.8,en,"War, Drama, Science Fiction",https://image.tmdb.org/t/p/original/lBhU4U9Eeh...

In [91]:
df.dtypes

Release_Date          object
Title                 object
Overview              object
Popularity           float64
Vote_Count            object
Vote_Average         float64
Original_Language     object
Genre                 object
Poster_Url            object
dtype: object

In [92]:
df.shape

(9837, 9)

In [93]:
df["Title"].unique()

array(['Spider-Man: No Way Home', 'The Batman', 'No Exit', ...,
       'The Offering', 'The United States vs. Billie Holiday', 'Threads'],
      shape=(9515,), dtype=object)

#### To handle missing values

In [94]:
df.isnull().sum()

Release_Date          0
Title                 9
Overview              9
Popularity           10
Vote_Count           10
Vote_Average         11
Original_Language    10
Genre                11
Poster_Url           11
dtype: int64

In [95]:
df=df.fillna(0)

In [96]:
df.isnull().sum()

Release_Date         0
Title                0
Overview             0
Popularity           0
Vote_Count           0
Vote_Average         0
Original_Language    0
Genre                0
Poster_Url           0
dtype: int64

#### To drop column

In [97]:
df=df.drop(["Poster_Url","Overview"],axis=1)

In [98]:
df.columns

Index(['Release_Date', 'Title', 'Popularity', 'Vote_Count', 'Vote_Average',
       'Original_Language', 'Genre'],
      dtype='object')

In [99]:
df

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Original_Language,Genre
0,15-12-2021,Spider-Man: No Way Home,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction"
1,01-03-2022,The Batman,3827.658,1151,8.1,en,"Crime, Mystery, Thriller"
2,25-02-2022,No Exit,2618.087,122,6.3,en,Thriller
3,24-11-2021,Encanto,2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy"
4,22-12-2021,The King's Man,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War"
...,...,...,...,...,...,...,...
9832,15-10-1973,Badlands,13.357,896,7.6,en,"Drama, Crime"
9833,01-10-2020,Violent Delights,13.356,8,3.5,es,Horror
9834,06-05-2016,The Offering,13.355,94,5.0,en,"Mystery, Thriller, Horror"
9835,31-03-2021,The United States vs. Billie Holiday,13.354,152,6.7,en,"Music, Drama, History"
9836,23-09-1984,Threads,13.354,186,7.8,en,"War, Drama, Science Fiction"

#### Data type correction

In [100]:
df["Release_Date"]=pd.to_datetime(df["Release_Date"],dayfirst=True,errors="coerce")
df["Vote_Count"]=pd.to_numeric(df["Vote_Count"],errors="coerce")

In [101]:
df.dtypes

Release_Date         datetime64[ns]
Title                        object
Popularity                  float64
Vote_Count                  float64
Vote_Average                float64
Original_Language            object
Genre                        object
dtype: object

In [102]:
df["Title"].unique()

array(['Spider-Man: No Way Home', 'The Batman', 'No Exit', ...,
       'The Offering', 'The United States vs. Billie Holiday', 'Threads'],
      shape=(9515,), dtype=object)

#### Group by

In [104]:
df.groupby("Title")["Vote_Count"].sum()

Title
0                                                   0.0
#Alive                                           1210.0
#AnneFrank. Parallel Stories                       35.0
#realityhigh                                      943.0
(500) Days of Summer                             8198.0
                                                  ...
xxxHOLiC The Movie: A Midsummer Night's Dream      21.0
¡A Volar, Joven!                                   83.0
¡Qué Despadre!                                      2.0
¡Three Amigos!                                    723.0
Æon Flux                                         1743.0
Name: Vote_Count, Length: 9515, dtype: float64

In [116]:
df1=df.groupby("Original_Language")["Vote_Average"].mean().reset_index()

In [117]:
df1.shape

(45, 2)

In [123]:
df1=df1.sort_values(by="Vote_Average",ascending=False)

In [124]:
df1

                                    Original_Language  Vote_Average
28                                                 ms      7.700000
43                                                 uk      7.650000
13                                                 fa      7.566667
1                                                  ar      7.450000
19                                                 hu      7.333333
5                                                  cs      7.300000
27                                                 ml      7.200000
25                                                 la      7.100000
37                                                 sv      7.021739
11                                                 et      7.000000
23                                                 ja      6.979225
35                                                 ru      6.855422
24                                                 ko      6.780588
8                                                  el      6.760000
44                                                 zh      6.736434
7                                                  de      6.729268
29                                                 nb      6.700000
21                                                 is      6.650000
17                                                 hi      6.626923
6                                                  da      6.607143
10                                                 es      6.576106
4                                                  cn      6.536697
40                                                 th      6.535294
22                                                 it      6.529268
33                                                 pt      6.475676
42                                                 tr      6.446667
31                                                 no      6.430769
38                                                 ta      6.400000
12                                                 eu      6.400000
9                                                  en      6.370643
30                                                 nl      6.333333
15                                                 fr      6.314726
34                                                 ro      6.250000
14                                                 fi      6.220000
16                                                 he      6.200000
32                                                 pl      6.111765
3                                                  ca      6.000000
36                                                 sr      5.700000
20                                                 id      5.533333
39                                                 te      5.350000
2                                                  bn      5.300000
41                                                 tl      4.325000
26                                                 lv      0.000000
18  https://image.tmdb.org/t/p/original/6iXYe7AkQ1...      0.000000
0                                                   0      0.000000

In [132]:
df2=df.groupby(df["Release_Date"].dt.year)["Vote_Count"].sum().reset_index()

In [133]:
df2

     Release_Date  Vote_Count
0          1902.0      1284.0
1          1920.0      1075.0
2          1921.0      1741.0
3          1922.0      1647.0
4          1925.0       840.0
..            ...         ...
97         2020.0    281151.0
98         2021.0    326021.0
99         2022.0     14111.0
100        2023.0         0.0
101        2024.0         0.0

[102 rows x 2 columns]

#### Output in Excel file

In [126]:
df.to_excel(r'C:\Users\DELL\Downloads\Netflix_Data.xlsx',index=False)